### ISSUE TITLE
Add a testing CI pipeline

### ISSUE THREAD

**Issue by saniales** [italia/publiccode-validator#13]
I suggest creating A Github Action to validate the code

reference: https://github.com/features/actions

**Comment by LucaPrete** [comment]
@saniales we have always used CircleCI or Azure DevOps, depending on the workflow.
Is there any specific reason for which you'd suggest to move to GH actions?
BTW, I'm not opposed to it. I've always had to find some time to dig more into it. For now, Circle has always done what we've asked for and we have good templates around for it, already used in other repos...

**Comment by LucaPrete** [comment]
@saniales you can find the config for this repo here: https://github.com/italia/publiccode-validator/blob/master/.circleci/config.yml

**Comment by saniales** [comment]
my bad, I just saw circleCI does not work on forks, so when you debug it it is a hassle.

**Comment by saniales** [comment]
closed by #14
