### ISSUE TITLE
Document the possible responses of the endpoint

### ISSUE THREAD

**Issue by bfabio** [italia/publiccode-validator#17]
Properly document what the endpoint is supposed to return, the format response and the HTTP states.

**Comment by sebbalex** [comment]
This was discusses long time ago, and for sure we can review it. The approach is described in openapi specs: https://github.com/italia/publiccode-validator/blob/master/api_spec_oa3.yml

**Comment by sebbalex** [comment]
We should consider closed this one based on new api definition, later #25 merge, wdyt @bfabio

**Comment by bfabio** [comment]
@sebbalex Agreed.
